export const BUILTIN_TEMPLATES = [
  {
    id: 'tpl-adrisu-kids',
    name: 'Adrisu Kids - Moda Infantil (Enterprise Multi-Ventana)',
    description: 'Tienda virtual de alta gama con imágenes fotográficas en HD, navegación por ventanas (Inicio, Niños, Niñas, Bebés, Ofertas), filtro por categorías, tallas y compra directa por WhatsApp.',
    industry: 'moda_infantil',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop',
    seo: {
      title: 'Adrisu Kids - Tienda Virtual Oficial de Moda Infantil',
      description: 'Prendas exclusivas en algodón 100% antialérgico para niños, niñas y bebés.',
    },
    settings: {
      primaryColor: '#f43f5e',
      secondaryColor: '#fff1f2',
      accentColor: '#ec4899',
      whatsappNumber: '51999888777',
    },
    blocks: [
      {
        id: 'ak-navbar',
        type: 'navbar',
        settings: { backgroundColor: '#ffffff', textColor: '#111827', accentColor: '#f43f5e' },
        content: {
          announcement: '✨ ¡ENVÍO GRATIS A TODO EL PERÚ EN COMPRAS MAYORES A S/ 120! 📦',
          brandName: 'ADRISU KIDS',
          links: [
            { label: 'Inicio', windowId: 'home', iconName: 'Home' },
            { label: 'Colección Niños', windowId: 'ninos', iconName: 'Shirt' },
            { label: 'Colección Niñas', windowId: 'ninas', iconName: 'Sparkles' },
            { label: 'Ropa Bebés', windowId: 'bebes', iconName: 'Baby' },
            { label: 'Ofertas Flash', windowId: 'ofertas', iconName: 'Flame' },
            { label: 'Contacto WhatsApp', windowId: 'whatsapp', iconName: 'MessageSquare' },
          ],
        },
      },
      {
        id: 'ak-hero',
        type: 'hero',
        settings: { backgroundColor: '#fff1f2', textColor: '#881337', accentColor: '#f43f5e', paddingY: 96 },
        content: {
          badge: 'NUEVA COLECCIÓN PRIMAVERA - VERANO 2026',
          title: 'Moda Feliz y Exclusiva para los Pequeños',
          subtitle: 'Diseños allergy-free en algodón 100% orgánico. Confort, resistencia y estilo para acompañar sus mejores aventuras.',
          buttonText: 'Ver Catálogo Completo',
          secondaryButtonText: 'Explorar Ofertas (30% OFF)',
          heroImage: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=1000&auto=format&fit=crop',
        },
      },
      {
        id: 'ak-products',
        type: 'product-grid',
        settings: { backgroundColor: '#ffffff', textColor: '#111827', accentColor: '#f43f5e', paddingY: 72 },
        content: {
          title: 'Catálogo de Moda Infantil — Selecciona tu Ventana',
          subtitle: 'Explora nuestras categorías exclusivas de ropa, calzado y accesorios',
          categoryTabs: [
            { id: 'all', label: 'Todos los Productos' },
            { id: 'ninos', label: 'Niños (2-14 años)' },
            { id: 'ninas', label: 'Niñas (2-14 años)' },
            { id: 'bebes', label: 'Bebés (0-24 meses)' },
            { id: 'ofertas', label: 'Ofertas Flash (30% OFF)' },
          ],
          products: [
            {
              id: 'p1',
              category: 'ninos',
              name: 'Conjunto Algodón Orgánico Dino Explorer',
              price: 'S/ 59.90',
              originalPrice: 'S/ 89.90',
              discountBadge: '-33% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&auto=format&fit=crop',
              sizes: ['2T', '4T', '6T', '8T'],
              description: 'Algodón peruano 100% peinado, transpirable y súper suave.',
            },
            {
              id: 'p2',
              category: 'ninas',
              name: 'Vestido Fiesta Primavera Florcita Rose',
              price: 'S/ 79.90',
              originalPrice: 'S/ 110.00',
              discountBadge: '-27% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop',
              sizes: ['4T', '6T', '8T', '10T'],
              description: 'Forro de franela suave con tul fantasía de alta durabilidad.',
            },
            {
              id: 'p3',
              category: 'ninos',
              name: 'Zapatillas Luces LED Confort Runner',
              price: 'S/ 99.90',
              originalPrice: 'S/ 139.90',
              discountBadge: '-28% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop',
              sizes: ['24', '26', '28', '30'],
              description: 'Suela antideslizante con batería LED recargable de larga duración.',
            },
            {
              id: 'p4',
              category: 'bebes',
              name: 'Pijama Enterizo Térmico Bebé Osito Velvet',
              price: 'S/ 45.00',
              originalPrice: 'S/ 65.00',
              discountBadge: '-30% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop',
              sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
              description: 'Cierre bidireccional para cambio rápido de pañal.',
            },
            {
              id: 'p5',
              category: 'ninos',
              name: 'Casaca Impermeable Capucha Osito Térmico',
              price: 'S/ 89.90',
              originalPrice: 'S/ 120.00',
              discountBadge: '-25% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop',
              sizes: ['4T', '6T', '8T', '12T'],
              description: 'Interior térmico de polar antipeeling y tela 100% repelente al agua.',
            },
            {
              id: 'p6',
              category: 'ninas',
              name: 'Set x3 Polos Manga Corta Algodón Supima',
              price: 'S/ 49.90',
              originalPrice: 'S/ 75.00',
              discountBadge: '-33% OFF',
              imageUrl: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=600&auto=format&fit=crop',
              sizes: ['2T', '4T', '6T', '8T'],
              description: 'Colores duraderos que soportan más de 50 lavadas sin decolorar.',
            },
          ],
        },
      },
      {
        id: 'ak-features',
        type: 'features',
        settings: { backgroundColor: '#fff8f6', textColor: '#111827', accentColor: '#f43f5e', paddingY: 64 },
        content: {
          title: '¿Por qué la Plataforma Adrisu Kids es la Elegida por las Familias?',
          items: [
            { iconName: 'Leaf', title: 'Algodón 100% Antialérgico', description: 'Cuidamos la piel sensible de tus hijos con tejidos orgánicos certificados sin químicos agresivos.' },
            { iconName: 'Truck', title: 'Envío Gratis a Nivel Nacional', description: 'Despachos en 24h para Lima y envíos asegurados por Olva Courier y Shalom a todo el Perú.' },
            { iconName: 'RefreshCw', title: 'Cambio de Talla Sin Costo Extra', description: 'Si la prenda no le queda perfecta a tu pequeño, realizamos el cambio a domicilio totalmente gratis.' },
            { iconName: 'ShieldCheck', title: 'Garantía Total de Satisfacción', description: 'Más de 15,000 mamás satisfechas respaldan la calidad de nuestros acabados.' },
          ],
        },
      },
      {
        id: 'ak-testimonials',
        type: 'testimonials',
        settings: { backgroundColor: '#ffffff', textColor: '#111827', paddingY: 64 },
        content: {
          title: 'Reseñas Verificadas de Compradoras',
          items: [
            { text: 'La ropa de Adrisu Kids es hermosísima y no se descolora al lavar. El algodón es súper suave y mis hijos están encantados.', name: 'Claudia M.', role: 'Mamá Verificada (San Borja)' },
            { text: 'Llegó en menos de 24 horas a Trujillo. La atención por WhatsApp fue muy amable y el empaque vino hermoso listo para regalo.', name: 'Valeria S.', role: 'Mamá Verificada (Trujillo)' },
            { text: 'Pedí 4 casacas y 2 conjuntos de dinosaurio. La talla fue exacta gracias a su guía y la calidad es nivel exportación.', name: 'Patricia L.', role: 'Mamá de Mateo (Surco)' },
          ],
        },
      },
      {
        id: 'ak-cta',
        type: 'cta',
        settings: { accentColor: '#f43f5e', paddingY: 80 },
        content: {
          title: '¡CUPÓN 15% OFF EXTRA EN TU PRIMERA COMPRA!',
          description: 'Únete al Club VIP Adrisu Kids por WhatsApp y recibe cupones de descuento exclusivos y sorpresas en el cumpleaños de tus hijos.',
          buttonText: 'Pedir por WhatsApp Ahora',
        },
      },
      {
        id: 'ak-countdown',
        type: 'countdown',
        settings: { accentColor: '#f43f5e', paddingY: 56 },
        content: {
          badge: 'Oferta Relámpago de Verano',
          title: 'Hasta 40% OFF en esta semana',
          subtitle: 'Stock limitado en prendas seleccionadas de la colección Primavera-Verano 2026.',
          endDate: '2026-09-01T23:59:59',
          buttonText: 'Ver Ofertas',
        },
      },
      {
        id: 'ak-faq',
        type: 'faq',
        settings: { backgroundColor: '#fff1f2', textColor: '#881337', accentColor: '#f43f5e', paddingY: 64 },
        content: {
          title: 'Preguntas Frecuentes',
          subtitle: 'Todo lo que necesitas saber antes de comprar',
          items: [
            { question: '¿Cuánto tarda el envío a mi ciudad?', answer: 'Enviamos en 24 horas dentro de Lima Metropolitana y de 2 a 4 días hábiles a todo el Perú vía Olva o Shalom. Incluye número de seguimiento por WhatsApp.' },
            { question: '¿Cómo sé qué talla elegir?', answer: 'Cada producto incluye una guía de tallas detallada. Si tienes dudas, nuestro equipo te asesora gratis por WhatsApp antes de confirmar tu pedido.' },
            { question: '¿Puedo cambiar o devolver una prenda?', answer: 'Sí. Tienes 30 días para cambios por talla o color sin costo adicional. El cambio se coordina a domicilio y recogemos la prenda original.' },
            { question: '¿Cuáles son los medios de pago?', answer: 'Aceptamos Yape, Plin, transferencia bancaria, tarjetas y contra entrega en Lima. Los pagos digitales reciben un cupón de bienvenida.' },
          ],
        },
      },
      {
        id: 'ak-newsletter',
        type: 'newsletter',
        settings: { backgroundColor: '#881337', textColor: '#ffffff', accentColor: '#f43f5e', paddingY: 48 },
        content: {
          title: 'Únete al Club VIP Adrisu Kids',
          subtitle: 'Cupones exclusivos, novedades y sorpresas en el cumpleaños de tus hijos.',
          buttonText: 'Quiero Cupones',
        },
      },
      {
        id: 'ak-social-proof',
        type: 'social-proof',
        settings: { enabled: true, interval: 7, accentColor: '#f43f5e' },
        content: {
          messages: [
            'Claudia de San Borja acaba de comprar el Conjunto Dino Explorer 🛍️',
            'Valeria de Trujillo compró el Vestido Primavera Florcita Rose 🛍️',
            'Patricia de Surco se llevó la Casaca Osito Térmico 🛍️',
            'María de Miraflores compró el Set x3 Polos Algodón Supima 🛍️',
          ],
        },
      },
      {
        id: 'ak-footer',
        type: 'footer',
        settings: { backgroundColor: '#881337', textColor: '#ffffff', paddingY: 48 },
        content: {
          brandName: 'ADRISU KIDS PERÚ — OFICIAL',
          copyright: '© 2026 Adrisu Kids Perú. Todos los derechos reservados. Impulsado por WMS Enterprise Platform.',
        },
      },
    ],
  },
  {
    id: 'tpl-tech-vibes',
    name: 'TechVibes - Electrónica & Gadgets (Enterprise Multi-Ventana)',
    description: 'Tienda de tecnología con fotografía HD de gadgets, ventanas de categorías (Audio, Wearables, Gaming, Carga), dark mode neón y botones de compra instantánea.',
    industry: 'tecnologia',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop',
    seo: {
      title: 'TechVibes - Tienda Oficial de Gadgets & Tecnología',
      description: 'Audífonos inalámbricos, smartwatches y accesorios tech con 12 meses de garantía.',
    },
    settings: {
      primaryColor: '#3b82f6',
      secondaryColor: '#0f172a',
      accentColor: '#8b5cf6',
      whatsappNumber: '51999888777',
    },
    blocks: [
      {
        id: 'tv-navbar',
        type: 'navbar',
        settings: { backgroundColor: '#090d16', textColor: '#ffffff', accentColor: '#3b82f6' },
        content: {
          announcement: '⚡ GARANTÍA OFICIAL 12 MESES + ENVÍO EXPRESS EN 2 HORAS EN LIMA 🚀',
          brandName: 'TECHVIBES',
          links: [
            { label: 'Inicio', windowId: 'home', iconName: 'Home' },
            { label: 'Audio & Headsets', windowId: 'audio', iconName: 'Headphones' },
            { label: 'Smartwatches', windowId: 'watches', iconName: 'Watch' },
            { label: 'Carga & Energía', windowId: 'carga', iconName: 'Zap' },
            { label: 'Ofertas Flash', windowId: 'ofertas', iconName: 'Flame' },
          ],
        },
      },
      {
        id: 'tv-hero',
        type: 'hero',
        settings: { backgroundColor: '#090d16', textColor: '#ffffff', accentColor: '#3b82f6', paddingY: 96 },
        content: {
          badge: 'TECNOLOGÍA DE NIVEL ENTERPRISE 2026',
          title: 'TechVibes — Experiencia Audiovisual de Siguiente Nivel',
          subtitle: 'Audífonos Hi-Fi con Cancelación Activa de Ruido (ANC), Relojes Inteligentes AMOLED y Periféricos Gamer con Garantía Oficial.',
          buttonText: 'Explorar Gadgets Tech',
          secondaryButtonText: 'Ofertas Relámpago',
          heroImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop',
        },
      },
      {
        id: 'tv-products',
        type: 'product-grid',
        settings: { backgroundColor: '#0f172a', textColor: '#ffffff', accentColor: '#3b82f6', paddingY: 72 },
        content: {
          title: 'Parrilla Tecnológica — Selecciona tu Ventana',
          subtitle: 'Gadgets seleccionados con prueba de rendimiento y despacho inmediato',
          categoryTabs: [
            { id: 'all', label: 'Todos los Gadgets' },
            { id: 'audio', label: 'Audio Hi-Fi' },
            { id: 'watches', label: 'Smartwatches' },
            { id: 'carga', label: 'Carga Rápida GaN' },
          ],
          products: [
            { id: 't1', category: 'audio', name: 'Audífonos ANC Pro Bass Noise Cancelling 5.3', price: 'S/ 189.00', originalPrice: 'S/ 260.00', discountBadge: '-27% OFF', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop', description: 'Autonomía de 40 horas continuas y driver dinámico de 40mm.' },
            { id: 't2', category: 'watches', name: 'Smartwatch AMOLED Ultra Fit 2 GPS', price: 'S/ 229.00', originalPrice: 'S/ 310.00', discountBadge: '-26% OFF', imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop', description: 'Monitoreo cardíaco 24/7, SpO2 y resistencia al agua 5 ATM.' },
            { id: 't3', category: 'carga', name: 'Cargador Carga Rápida GaN 65W Triple Puerto', price: 'S/ 89.00', originalPrice: 'S/ 120.00', discountBadge: '-25% OFF', imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop', description: 'Carga tu laptop y smartphone en simultáneo con protocolo PD 3.0.' },
            { id: 't4', category: 'audio', name: 'Teclado Mecánico RGB Wireless Hot-Swap 60%', price: 'S/ 249.00', originalPrice: 'S/ 320.00', discountBadge: '-22% OFF', imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop', description: 'Switches mecánicos amarillos silenciosos con latencia ultra baja de 1ms.' },
          ],
        },
      },
      {
        id: 'tv-features',
        type: 'features',
        settings: { backgroundColor: '#090d16', textColor: '#ffffff', accentColor: '#3b82f6', paddingY: 64 },
        content: {
          title: 'La Garantía TechVibes',
          items: [
            { iconName: 'ShieldCheck', title: 'Garantía Real 12 Meses', description: 'Reemplazo directo de producto si presenta algún defecto de fábrica.' },
            { iconName: 'Truck', title: 'Envío Express 2 Horas', description: 'Envíos veloces en Lima Metropolitana y despachos diarios a provincias.' },
            { iconName: 'CreditCard', title: 'Pago Contra Entrega', description: 'Paga con Yape, Plin o efectivo al recibir tu pedido en la puerta de tu casa.' },
            { iconName: 'RefreshCw', title: 'Soporte Técnico 24/7', description: 'Asesoría técnica para configuración y sincronización por WhatsApp.' },
          ],
        },
      },
      {
        id: 'tv-testimonials',
        type: 'testimonials',
        settings: { backgroundColor: '#0f172a', textColor: '#ffffff', paddingY: 64 },
        content: {
          title: 'Reseñas de la Comunidad Tech',
          items: [
            { text: 'Los audífonos ANC cancelan el ruido del tráfico a la perfección. La batería me dura toda la semana laboral.', name: 'Renzo G.', role: 'Desarrollador Software (Miraflores)' },
            { text: 'El reloj AMOLED mide mis carreras con GPS exacto. Llegó súper rápido a Arequipa.', name: 'Diego P.', role: 'Runner & Tech Enthusiast' },
            { text: 'Excelente atención al cliente. Me dieron asesoría por WhatsApp para elegir el teclado mecánico perfecto.', name: 'Fiorella V.', role: 'Diseñadora Gamer' },
          ],
        },
      },
      {
        id: 'tv-cta',
        type: 'cta',
        settings: { accentColor: '#3b82f6', paddingY: 80 },
        content: {
          title: 'OFERTAS FLASH HASTA 40% OFF',
          description: 'Stock limitado. Haz tu pedido por WhatsApp antes de que se agoten las unidades promocionales.',
          buttonText: 'Comprar por WhatsApp',
        },
      },
      {
        id: 'tv-countdown',
        type: 'countdown',
        settings: { accentColor: '#3b82f6', paddingY: 56 },
        content: {
          badge: 'Gaming Week · Ofertas Tech',
          title: 'La semana más tecnológica del año',
          subtitle: 'Descuentos de hasta 40% en audio Hi-Fi, smartwatches y periféricos gamer.',
          endDate: '2026-08-25T23:59:59',
          buttonText: 'Explorar Ofertas',
        },
      },
      {
        id: 'tv-faq',
        type: 'faq',
        settings: { backgroundColor: '#0f172a', textColor: '#ffffff', accentColor: '#3b82f6', paddingY: 64 },
        content: {
          title: 'Preguntas Frecuentes Tech',
          subtitle: 'Resolvemos tus dudas antes de comprar',
          items: [
            { question: '¿Los productos tienen garantía real?', answer: 'Sí, todos nuestros productos incluyen 12 meses de garantía oficial con reemplazo directo ante defectos de fábrica, sin vueltas innecesarias.' },
            { question: '¿Cómo funciona el envío express de 2 horas?', answer: 'En Lima Metropolitana despachamos en 2 horas dentro de los distritos de cobertura. A provincia enviamos vía agencia con seguimiento.' },
            { question: '¿Puedo pagar contra entrega?', answer: 'Claro. Aceptamos Yape, Plin, efectivo y tarjetas. El contra entrega está disponible en Lima Metropolitana.' },
            { question: '¿Me ayudan con la configuración de mis gadgets?', answer: 'Nuestro soporte técnico por WhatsApp te guía paso a paso con la sincronización y configuración de cualquier dispositivo.' },
          ],
        },
      },
      {
        id: 'tv-newsletter',
        type: 'newsletter',
        settings: { backgroundColor: '#030712', textColor: '#ffffff', accentColor: '#3b82f6', paddingY: 48 },
        content: {
          title: 'Recibe ofertas exclusivas Tech',
          subtitle: 'Acceso anticipado a lanzamientos y cupones solo para suscriptores.',
          buttonText: 'Suscribirme',
        },
      },
      {
        id: 'tv-social-proof',
        type: 'social-proof',
        settings: { enabled: true, interval: 7, accentColor: '#3b82f6' },
        content: {
          messages: [
            'Renzo de Miraflores compró los Audífonos ANC Pro 🎧',
            'Diego de Arequipa compró el Smartwatch AMOLED Ultra Fit 🎧',
            'Fiorella de La Molina se llevó el Teclado Mecánico RGB 🎧',
            'Carlos de San Isidro compró el Cargador GaN 65W 🎧',
          ],
        },
      },
      {
        id: 'tv-footer',
        type: 'footer',
        settings: { backgroundColor: '#030712', textColor: '#ffffff', paddingY: 48 },
        content: {
          brandName: 'TECHVIBES STORE',
          copyright: '© 2026 TechVibes. Impulsado por WMS Platform.',
        },
      },
    ],
  },
  {
    id: 'tpl-boutique-gourmet',
    name: 'Boutique Gourmet - Vinos & Cava (Enterprise Multi-Ventana)',
    description: 'Diseño distinguido con fotografías HD de vinos de reserva, queso madurado y hampers, con navegación por ventanas de Cava y Regalos Corporativos.',
    industry: 'gastronomia',
    category: 'ecommerce',
    thumbnail: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&auto=format&fit=crop',
    seo: {
      title: 'Boutique Gourmet - Vinos & Delicatessen',
      description: 'Vinos de gran reserva, quesos madurados y hampers de regalo corporativo.',
    },
    settings: {
      primaryColor: '#78350f',
      secondaryColor: '#fef3c7',
      accentColor: '#d97706',
      whatsappNumber: '51999888777',
    },
    blocks: [
      {
        id: 'bg-navbar',
        type: 'navbar',
        settings: { backgroundColor: '#1c1917', textColor: '#fef3c7', accentColor: '#d97706' },
        content: {
          announcement: '🍷 ATENCIÓN SOMMELIER PERSONALIZADA & PACKS CORPORATIVOS 🎁',
          brandName: 'BOUTIQUE GOURMET',
          links: [
            { label: 'Inicio', windowId: 'home', iconName: 'Home' },
            { label: 'Cava & Vinos', windowId: 'vinos', iconName: 'Wine' },
            { label: 'Quesos Artisanal', windowId: 'quesos', iconName: 'Utensils' },
            { label: 'Cajas Regalo', windowId: 'regalos', iconName: 'Gift' },
          ],
        },
      },
      {
        id: 'bg-hero',
        type: 'hero',
        settings: { backgroundColor: '#1c1917', textColor: '#fef3c7', accentColor: '#d97706', paddingY: 96 },
        content: {
          badge: 'COSECHA SELECCIONADA & CAVA DE AUTOR',
          title: 'Boutique Gourmet — El Arte de Maridar Exquisito',
          subtitle: 'Vinos de cosecha seleccionada, quesos trufados madurados y cajas de regalo de lujo.',
          buttonText: 'Explorar Cava & Delicatessen',
          secondaryButtonText: 'Hampers Corporativos',
          heroImage: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1000&auto=format&fit=crop',
        },
      },
      {
        id: 'bg-products',
        type: 'product-grid',
        settings: { backgroundColor: '#ffffff', textColor: '#1c1917', accentColor: '#d97706', paddingY: 72 },
        content: {
          title: 'Nuestra Cava Seleccionada',
          subtitle: 'Vinos y maridajes curados por nuestro Sommelier certificado',
          categoryTabs: [
            { id: 'all', label: 'Toda la Cava' },
            { id: 'vinos', label: 'Vinos Reserva' },
            { id: 'quesos', label: 'Quesos Madurados' },
            { id: 'regalos', label: 'Hampers VIP' },
          ],
          products: [
            { id: 'g1', category: 'vinos', name: 'Vino Gran Reserva Malbec Mendoza 2018', price: 'S/ 165.00', originalPrice: 'S/ 210.00', discountBadge: '-21% OFF', imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop', description: 'Madurado 24 meses en barrica de roble francés.' },
            { id: 'g2', category: 'quesos', name: 'Queso Trufado Artesanal Madurado 300g', price: 'S/ 85.00', originalPrice: 'S/ 110.00', discountBadge: '-22% OFF', imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&auto=format&fit=crop', description: 'Elaborado con trufa negra silvestre importada.' },
            { id: 'g3', category: 'regalos', name: 'Tabla Jamón Serrano 100% Ibérico Reserva', price: 'S/ 120.00', originalPrice: 'S/ 150.00', discountBadge: '-20% OFF', imageUrl: 'https://images.unsplash.com/photo-1524182576066-1d963e941b71?w=600&auto=format&fit=crop', description: 'Curado artesanal de 36 meses en bodega tradicional.' },
            { id: 'g4', category: 'regalos', name: 'Box Sommelier (Vino + 2 Quesos + Mermelada)', price: 'S/ 290.00', originalPrice: 'S/ 360.00', discountBadge: '-19% OFF', imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop', description: 'Caja de madera tallada a mano lista para obsequio VIP.' },
          ],
        },
      },
      {
        id: 'bg-features',
        type: 'features',
        settings: { backgroundColor: '#fef3c7', textColor: '#1c1917', accentColor: '#d97706', paddingY: 64 },
        content: {
          title: 'El Sello de Excelencia Gourmet',
          items: [
            { iconName: 'Wine', title: 'Cava con Control de Temperatura', description: 'Conservamos cada botella a 14°C constantes para preservar su aroma y notas de cata.' },
            { iconName: 'Truck', title: 'Empaque Térmico Especial', description: 'Entregamos tus botellas y quesos en cajas isotérmicas con gel refrigerante.' },
            { iconName: 'Gift', title: 'Tarjeta Grabada de Regalo', description: 'Incluimos dedicatoria elegante en papel textura con sello de lacre.' },
            { iconName: 'ShieldCheck', title: 'Garantía de Maridaje', description: 'Asesoría en línea previa a tu compra con nuestro Sommelier.' },
          ],
        },
      },
      {
        id: 'bg-testimonials',
        type: 'testimonials',
        settings: { backgroundColor: '#ffffff', textColor: '#1c1917', paddingY: 64 },
        content: {
          title: 'Opiniones de Catadores & Clientes VIP',
          items: [
            { text: 'El Malbec Gran Reserva llegó a la temperatura perfecta para el descorche. La caja de regalo superó las expectativas de mi cliente corporativo.', name: 'Carlos E.', role: 'Gerente General (San Isidro)' },
            { text: 'El queso trufado es sensacional. Sin duda la mejor tienda delicatessen en Lima.', name: 'Lucía B.', role: 'Sommelier Aficionada' },
          ],
        },
      },
      {
        id: 'bg-cta',
        type: 'cta',
        settings: { accentColor: '#d97706', paddingY: 80 },
        content: {
          title: 'HAMPERS & REGALOS CORPORATIVOS VIP',
          description: 'Personalizamos tus cajas de regalo con grabado de marca y tarjeta personalizada.',
          buttonText: 'Cotizar con Sommelier por WhatsApp',
        },
      },
      {
        id: 'bg-countdown',
        type: 'countdown',
        settings: { accentColor: '#d97706', paddingY: 56 },
        content: {
          badge: 'Venta de Reserva Especial',
          title: 'Packs maridaje con 25% OFF',
          subtitle: 'Selección limitada de vinos Gran Reserva y quesos trufados para este fin de semana.',
          endDate: '2026-08-30T23:59:59',
          buttonText: 'Ver la Cava',
        },
      },
      {
        id: 'bg-faq',
        type: 'faq',
        settings: { backgroundColor: '#fef3c7', textColor: '#1c1917', accentColor: '#d97706', paddingY: 64 },
        content: {
          title: 'Preguntas Frecuentes',
          subtitle: 'Consejos de conservación y envío de nuestra cava',
          items: [
            { question: '¿Cómo conservan los vinos durante el envío?', answer: 'Usamos empaque térmico con gel refrigerante para mantener la temperatura ideal de 14°C durante todo el trayecto, incluso a provincia.' },
            { question: '¿Cuánto tiempo duran los quesos artesanales?', answer: 'Nuestros quesos madurados se conservan perfectamente refrigerados entre 30 y 60 días según la variedad. Incluyen fecha de consumo recomendado.' },
            { question: '¿Puedo personalizar una caja de regalo corporativa?', answer: 'Sí. Grabamos tu marca en la madera, incluimos tarjeta con dedicatoria y podemos entregar múltiples unidades con facturación corporativa.' },
            { question: '¿Ofrecen asesoría de maridaje?', answer: 'Nuestro Sommelier te asesora gratis por WhatsApp para elegir el maridaje perfecto según tu ocasión o presupuesto.' },
          ],
        },
      },
      {
        id: 'bg-newsletter',
        type: 'newsletter',
        settings: { backgroundColor: '#0c0a09', textColor: '#fef3c7', accentColor: '#d97706', paddingY: 48 },
        content: {
          title: 'Únete al Club Gourmet',
          subtitle: 'Catas privadas, vinos de añada y descuentos solo para socios.',
          buttonText: 'Quiero Invitaciones',
        },
      },
      {
        id: 'bg-social-proof',
        type: 'social-proof',
        settings: { enabled: true, interval: 8, accentColor: '#d97706' },
        content: {
          messages: [
            'Carlos de San Isidro compró el Malbec Gran Reserva 2018 🍷',
            'Lucía de Surco compró el Queso Trufado Artesanal 🍷',
            'Empresa XYZ cotizó 12 hampers corporativos VIP 🍷',
            'Valeria de Miraflores compró el Box Sommelier 🍷',
          ],
        },
      },
      {
        id: 'bg-footer',
        type: 'footer',
        settings: { backgroundColor: '#0c0a09', textColor: '#fef3c7', paddingY: 48 },
        content: {
          brandName: 'BOUTIQUE GOURMET PERÚ',
          copyright: '© 2026 Boutique Gourmet.',
        },
      },
    ],
  },
]
