import { BlockConfig } from '../types'

export const heroBlock: BlockConfig = {
  id: 'hero',
  name: 'Hero Section',
  description: 'Main hero banner with title, subtitle and CTA',
  category: 'layout',
  icon: 'Layout',
  defaultSettings: {
    variant: 'centered',
    height: 'full',
    backgroundType: 'color',
    backgroundColor: '#2563eb',
    backgroundImage: '',
    textColor: '#ffffff',
    overlayOpacity: 50,
    textAlign: 'center',
    paddingY: '80px',
    animation: 'fade-up',
  },
  defaultContent: {
    title: 'Your Headline Here',
    subtitle: 'A compelling subheading that explains your value proposition.',
    badge: '',
    heroImage: '',
    buttonText: 'Get Started',
    buttonLink: '#',
    buttonVariant: 'primary',
    secondaryButtonText: '',
    secondaryButtonLink: '',
  },
  settingsSchema: [
    { key: 'variant', label: 'Variant', type: 'select', options: [
      { label: 'Centered', value: 'centered' },
      { label: 'Left Aligned', value: 'left' },
      { label: 'Right Aligned', value: 'right' },
      { label: 'Split (Image + Text)', value: 'split' },
    ]},
    { key: 'height', label: 'Height', type: 'select', options: [
      { label: 'Full Screen', value: 'full' },
      { label: 'Auto', value: 'auto' },
      { label: 'Medium', value: 'medium' },
    ]},
    { key: 'backgroundType', label: 'Background Type', type: 'select', options: [
      { label: 'Color', value: 'color' },
      { label: 'Image', value: 'image' },
      { label: 'Gradient', value: 'gradient' },
    ]},
    { key: 'backgroundColor', label: 'Background Color', type: 'color' },
    { key: 'backgroundImage', label: 'Background Image URL', type: 'image' },
    { key: 'textColor', label: 'Text Color', type: 'color' },
    { key: 'overlayOpacity', label: 'Overlay Opacity', type: 'slider', min: 0, max: 100, step: 5 },
    { key: 'textAlign', label: 'Text Alignment', type: 'select', options: [
      { label: 'Center', value: 'center' },
      { label: 'Left', value: 'left' },
      { label: 'Right', value: 'right' },
    ]},
    { key: 'paddingY', label: 'Vertical Padding', type: 'select', options: [
      { label: 'Small (40px)', value: '40px' },
      { label: 'Medium (80px)', value: '80px' },
      { label: 'Large (120px)', value: '120px' },
      { label: 'Extra Large (160px)', value: '160px' },
    ]},
    { key: 'title', label: 'Title', type: 'text', group: 'content' },
    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'content' },
    { key: 'badge', label: 'Badge / Etiqueta superior', type: 'text', group: 'content' },
    { key: 'heroImage', label: 'Imagen del Hero', type: 'image', group: 'content' },
    { key: 'buttonText', label: 'Button Text', type: 'text', group: 'content' },
    { key: 'buttonLink', label: 'Button Link', type: 'link', group: 'content' },
    { key: 'secondaryButtonText', label: 'Secondary Button Text', type: 'text', group: 'content' },
    { key: 'secondaryButtonLink', label: 'Secondary Button Link', type: 'link', group: 'content' },
  ],
}
